title: Elena Luchina
logo: /assets/img/headshot_circular.png
description: Data Scientist | MIT Graduate Student | 5 years in Trade Marketing (Pharmacy, E-Commerce, Retail)
theme: jekyll-theme-minimal
