title: Elena Luchina
#logo: /assets/img/headshot_circle.png
#description: Data Scientist | MIT Graduate Student | 5 years in Trade Marketing (Pharmacy, E-Commerce, Retail)
theme: jekyll-theme-minimal
